version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=qualimente/terraform-spec:latest -t qualimente/terraform-spec:latest .
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
            if beginswith v "$CIRCLE_TAG" || [ ${CIRCLE_BRANCH} == "master" ]; then
              echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USER} --password-stdin
              docker push qualimente/terraform-spec:latest
            else
              echo "Skipping deploy"
            fi