version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: set BUILD_ID
          command: |
            BUILD_TIMESTAMP_UTC=$(date -u +'%Y%m%d-%H%M')
            BUILD_COMMIT_SHORT=$(git rev-parse --short HEAD)
            echo "export BUILD_COMMIT_SHORT=${BUILD_COMMIT_SHORT}" >> $BASH_ENV
            echo "export BUILD_TIMESTAMP_UTC=${BUILD_TIMESTAMP_UTC}" >> $BASH_ENV
            echo "export BUILD_ID=${BUILD_TIMESTAMP_UTC}-${BUILD_COMMIT_SHORT}" >> $BASH_ENV
      - run:
          name: Build application Docker image
          command: |
            source $BASH_ENV
            docker build --cache-from=qualimente/terraform-infra-dev:latest -t qualimente/terraform-infra-dev:latest -t qualimente/terraform-infra-dev:${BUILD_ID} .
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            source $BASH_ENV
            beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
            if beginswith v "$CIRCLE_TAG" || [ ${CIRCLE_BRANCH} == "master" ]; then
              echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
              for tag in latest "${BUILD_ID}"
              do
                docker push qualimente/terraform-infra-dev:${tag}
              done;
            else
              echo "Skipping deploy"
            fi